plugins:
  custom_pages_enabled:
    default: true
    client: false

  custom_pages_templates:
    type: text
    default: |
      {
        "landing": {
          "title": "Landing",
          "mode": "inline",
          "html": "<section><h1>Hola</h1><p>Bienvenid@s</p></section>",
          "css": "body { margin:0; font-family: system-ui; } h1 { color: #0ea5e9; }",
          "js": "console.log('landing lista');"
        },
        "tools": {
          "title": "Herramientas",
          "mode": "iframe",
          "html": "<div><h1>Tools</h1><button onclick=alert('ok')>Test</button></div>",
          "css": "html{background:#111;color:#eee}",
          "js": "console.log('tools iframe')"
        },
        "editor": {
          "title": "Editor",
          "mode": "inline",
          "html": "<div class=\"editor-wrap\">\n  <aside class=\"editor-sidebar\">\n    <h2>Índice</h2>\n    <ul>\n      <li>Sección 1</li>\n      <li>Sección 2</li>\n    </ul>\n  </aside>\n  <main class=\"editor-content\">\n    <h1>Bienvenid@ a editor</h1>\n    <p>Este contenido recrea la estética del archivo "editor".</p>\n    <button class=\"editor-action\">Probar acción</button>\n  </main>\n</div>",
          "css": " .editor-wrap { display:flex; gap:1rem; font-family: system-ui, -apple-system, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial; color:#111; } .editor-sidebar{width:220px;background:#fafafa;padding:1rem;border-right:1px solid #e5e7eb;border-radius:6px;} .editor-content{flex:1;padding:1rem;background:#fff;border-radius:6px;} .editor-action{background:#0ea5e9;color:#fff;border:none;padding:.5rem 1rem;border-radius:6px;cursor:pointer;} @media(max-width:700px){.editor-wrap{flex-direction:column}.editor-sidebar{width:100%;border-right:none;border-bottom:1px solid #e5e7eb}}",
          "js": "document.querySelectorAll('.editor-action').forEach(btn=>btn.addEventListener('click',()=>alert('Acción de editor ejecutada')));"
        }
      }
    client: true
    description:
      es: "JSON/YAML de páginas: {slug: {title, mode:inline|iframe, html, css, js}}"
