plugins:
  custom_pages_enabled:
    default: true
    client: false

  custom_pages_templates:
    type: text
    default: ""
    client: true
    description:
      es: "JSON/YAML de páginas: {slug: {title, mode:inline|iframe, html, css, js}}"

  custom_pages_templates_language:
    type: enum
    default: yaml
    client: true
    enum: 
      - yaml
      - json
      - javascript
      - htmlmixed
      - css
      - markdown
      - handlebars